Vagrant.configure("2") do |config|
  config.cache.auto_detect = true
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
Vagrant::Config.run do |config|

  {
    :'puppet' => {
      :os         => 'default',
      :hostname   => 'puppet.example42.com',
      :puppetmode => 'apply',
      :ip         => '10.42.42.10',
      :forwards   => { 80 => 8010, 443 => 44310 },
    },
    :'puppetdb' => {
      :os         => 'default',
      :hostname   => 'puppetdb.example42.com',
      :puppetmode => 'apply',
      :ip         => '10.42.42.9',
      :forwards   => { 80 => 8009, 443 => 44309 },
    },
    :'foreman' => {
      :os         => 'default',
      :hostname   => 'foreman.example42.com',
      :puppetmode => 'apply',
      :ip         => '10.42.42.8',
      :forwards => { 80 => 8008, 443 => 44308, },
    },
    :'syslog' => {
      :os         => 'default',
      :hostname   => 'syslog.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.15',
      :forwards   => { 80 => 8015, 443 => 44315, },
    },
    :'nagios' => {
      :os         => 'default',
      :hostname   => 'nagios.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.11',
      :forwards   => { 80 => 8011, 443 => 44311, },
    },
    :'munin' => {
      :os         => 'default',
      :hostname   => 'munin.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.15',
      :forwards   => { 80 => 8015, 443 => 44315, },
    },
    :'mq' => {
      :os         => 'default',
      :hostname   => 'syslog.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.41',
      :forwards   => { 80 => 8041, 443 => 44341, },
    },
    :'ldap1' => {
      :os         => 'default',
      :hostname   => 'ldap1.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.5',
      :forwards   => { 80 => 8005, 443 => 44305, },
    },

    :'test-centos5' => {
      :os         => 'Centos5',
      :hostname   => 'test-centos5.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.25',
      :forwards   => { 80 => 8025, 443 => 44325, },
    },
    :'test-centos6' => {
      :os         => 'Centos6',
      :hostname   => 'test-centos6.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.26',
      :forwards   => { 80 => 8026, 443 => 44326, },
    },
    :'test-ubuntu1204' => {
      :os         => 'Ubuntu1204',
      :hostname   => 'test-ubuntu1204.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.35',
      :forwards   => { 80 => 8035, 443 => 44335, },
    },
    :'test-ubuntu1004' => {
      :os         => 'Ubuntu1004',
      :hostname   => 'test-ubuntu1004.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.24',
      :forwards   => { 80 => 8024, 443 => 44324, },
    },
    :'test-debian6' => {
      :os         => 'Debian6',
      :hostname   => 'test-debian6.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.22',
      :forwards   => { 80 => 8022, 443 => 44322, },
    },
    :'test-opensuse11' => {
      :os         => 'OpenSuse11',
      :hostname   => 'test-opensuse11.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.37',
      :forwards   => { 80 => 8037, 443 => 44337, },
    },
    :'test-opensuse12' => {
      :os         => 'OpenSuse12',
      :hostname   => 'test-opensuse12.example42.com',
      :puppetmode => 'agent',
      :ip         => '10.42.42.38',
      :forwards   => { 80 => 8038, 443 => 43338, },
    },
  }.each do |name,cfg|
    config.vm.define name do |local|

      local.vm.host_name = cfg[:hostname] if cfg[:hostname]
      local.vm.network :hostonly, cfg[:ip] if cfg[:ip]

      local.vm.box_url = case cfg[:os]
        when 'Centos5' then 'http://vagrant-jls.objects.dreamhost.com/CentOS-5.9-x86_64-minimal.box'
        when 'Centos6' then 'http://vagrant-jls.objects.dreamhost.com/CentOS-6.4-x86_64-minimal.box'
        when 'Fedora18' then 'http://vagrant-jls.objects.dreamhost.com/Fedora-18-x86_64.box'
        when 'Debian5' then 'http://vagrant-jls.objects.dreamhost.com/Debian-5.0.10-amd64-netboot.box'
        when 'Debian6' then 'http://vagrant-jls.objects.dreamhost.com/Debian-6.0.7-amd64-netboot.box'
        when 'Debian7' then 'http://vagrant-jls.objects.dreamhost.com/Debian-7.0-rc1-amd64-netboot.box'
        when 'Ubuntu804' then 'http://vagrant-jls.objects.dreamhost.com/ubuntu-8.04.4-server-amd64.box'
        when 'Ubuntu1004' then 'http://vagrant-jls.objects.dreamhost.com/ubuntu-10.04.4-server-amd64.box'
        when 'Ubuntu1204' then 'http://vagrant-jls.objects.dreamhost.com/ubuntu-12.04.2-server-amd64.box'
        when 'OpenSuse11' then 'http://vagrant-jls.objects.dreamhost.com/openSUSE-11.4-NET-x86_64.box'
        when 'Scientific5' then 'http://vagrant-jls.objects.dreamhost.com/scientificlinux-5.9-x86_64-netboot.box'
        when 'Scientific6' then 'http://vagrant-jls.objects.dreamhost.com/scientificlinux-6.3-x86_64-netboot.box'
        else 'http://vagrant-jls.objects.dreamhost.com/CentOS-6.4-x86_64-minimal.box'
      end
      local.vm.box = local.vm.box_url.split('/').last

      if cfg[:forwards]
        cfg[:forwards].each do |from,to|
          local.vm.forward_port from, to
        end
      end

#      local.vm.provision :puppet_server do |puppet|
#        puppet.puppet_server = "puppet.example42.com" if cfg[:puppetmode] == "agent"
#      end
      local.vm.provision :puppet do |puppet|
        puppet.manifests_path = "manifests" if cfg[:puppetmode] != "agent"
        puppet.module_path = "modules" if cfg[:puppetmode] != "agent"
        puppet.manifest_file = "init.pp" if cfg[:puppetmode] != "agent"
        puppet.options = [
          '--verbose',
          '--debug',
        ]
      end

#      local.vm.boot_mode = :gui

    end
  end
end

