forge "http://forge.puppetlabs.com"

mod 'example42/puppi',
  :git => 'https://github.com/example42/puppi.git'

mod 'example42/puppet',
  :git => 'https://github.com/example42/puppet-puppet.git'

mod 'example42/mysql',
  :git => 'https://github.com/example42/puppet-puppet.git'

mod 'example42/monitor',
  :git => 'https://github.com/example42/puppet-monitor.git'

mod 'example42/firewall',
  :git => 'https://github.com/example42/puppet-firewall.git'

mod 'example42/iptables',
  :git => 'https://github.com/example42/puppet-iptables.git'

mod 'ripienaar/concat'

mod 'example42/apache',
  :git => 'https://github.com/example42/puppet-apache.git'

mod 'example42/yum',
  :git => 'https://github.com/example42/puppet-yum.git'


